### ISSUE TITLE
some lookup-refs fail

### ISSUE THREAD

**Issue by markusalbertgraf** [replikativ/datahike#122] opened 2020-02-15 16:23 UTC
Hi,
I use the `uuid`s with `cardinality many` and `unique identity`.
Some  lookups by lookup-ref fail.
I have written a minimal case that reproduces the error on my machine in about a third of the lookups here:
https://github.com/markusalbertgraf/datahike-uuid-lookup
please check whether you can reproduce this.

**Comment by whilo** [comment] 2020-02-15 22:31
Thank you for taking the time to factor out the error. Interestingly it seems to be UUID specific, I cannot reproduce it if I stringify the UUIDs.

**Comment by whilo** [comment] 2020-02-15 23:49
I have quickly ruled out that it is the UUID comparator in the hitchhiker-tree, it does not seem to be the problem.

**Comment by markusalbertgraf** [comment] 2020-02-16 10:24
Thank you for your quick response. I just observed that switching the db from file to mem more than doubles the error-rate, from around 30% to above 70% on my machine.

**Comment by whilo** [comment] 2020-02-16 20:22
Interesting, that means it is not hitchhiker-tree related. @kordano I therefore suspect that the insertion logic is having an edge case triggered by UUIDs.

**Comment by markusalbertgraf** [comment] 2020-02-17 09:50
I just checked squuids.  They do *not* trigger the error.  That's why my app works and the foreign keys introduced the problem.
```
(defn squuid []
  (let [uuid (java.util.UUID/randomUUID)
        time (System/currentTimeMillis)
        secs (quot time 1000)
        lsb  (.getLeastSignificantBits uuid)
        msb  (.getMostSignificantBits uuid)
        time-msb (bit-or (bit-shift-left secs 32)
                         (bit-and 0x00000000ffffffff msb))]
    (java.util.UUID. time-msb lsb)))
```

**Comment by markusalbertgraf** [comment] 2020-02-17 19:21
When I checked different backends I noticed that while with a db of 1000 entities mem had the most errors with 10 entities it had the least.  So out of curiosity I plottet the error frequency per backend per number of entities.  The result may or may not be useful to find the bug but it is definitely peculiar if not spectacular.  The range of error percentage stabilizes with the number of entities as one would expect but close to 600 entities the graph changes for all backends but in different ways.  But see for yourself.  This is propably more for fun and laughs than for debugging ;-)
See this graph: https://github.com/markusalbertgraf/datahike-uuid-lookup/blob/master/Fehlerh%C3%A4ufigkeit-2048-1000.svg

**Comment by whilo** [comment] 2020-02-18 20:33
@purrgrammer You have fixed the UUID support in the hitchhiker-tree and mentioned that the comparator is broken in Java. Can you elaborate with a few sentences on this? Maybe that helps to pin down the issue.

**Comment by whilo** [comment] 2020-02-18 20:36
@markusalbertgraf That is a very nice plot, I wish more debugging was done visually and with descriptive statistics. I am not sure how helpful it is to find the bug, but it will be interesting to interpret afterwards at least.

**Comment by markusalbertgraf** [comment] 2020-02-19 09:27
Just to clarify: It is only the `lookup ref` that fails.
So this fails:
```
(d/pull @conn '[*]
   [:uuid xxxxx])
```
but this works:
```
(d/pull @conn '[*]
   (d/q '[:find ?e .
            :in $ ?v
            :where
           [?e :uuid ?v]]
        @conn xxxxx))
```
and can serve as a workaround.

**Comment by purrgrammer** [comment] 2020-02-20 16:12
> @purrgrammer You have fixed the UUID support in the hitchhiker-tree and mentioned that the comparator is broken in Java. Can you elaborate with a few sentences on this? Maybe that helps to pin down the issue.

Sorry I didn't have time to look deeply into this issue not much free time at the moment unfortunately. 

To elaborate a bit more on the changes to UUID handling, there is a [Java bug](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7025832) in UUID comparison implementation: it does a numerical compare of the most and least-significant bits of the UUID (encoded as two Long), but Long type is encoded as a two-complement.

**Comment by ajoberstar** [comment] 2020-11-30 19:41
FYI, @markusalbertgraf noted that #258 is the same issue as this, and I think I've [tracked down the cause](https://github.com/replikativ/datahike/issues/258#issuecomment-735998099).

Might look a little into the necessary hitchhiker-tree change, but would be interested in feedback on how the maintainers would like it fixed.

**Closed** 2021-04-09 15:21 UTC
