### ISSUE TITLE
ref to missing entity

### ISSUE THREAD

**Issue by filipesilva** [replikativ/datahike#394] opened 2021-09-29 10:52 UTC
While working on a database, I ended up in a state where there's a ref to an entity that doesn't exist anymore.

Steps to repro:
- `git clone https://github.com/filipesilva/datahike-broken-ref`
- `cd datahike-broken-ref`
- `clj -X repro/run`

You can see similar to the following log, where the first object is a pull for entity 194, and subsequent objects are different attempts to get entity 258 (referenced in :block/children for 194). Entity 258 does not seem to exist anymore. It did exist at some point though, and then was removed.

```
{:db/id 194,
 :block/children
 [#:db{:id 195}
  #:db{:id 207}
  #:db{:id 220}
  #:db{:id 224}
  #:db{:id 227}
  #:db{:id 228}
  #:db{:id 229}
  #:db{:id 230}
  #:db{:id 231}
  #:db{:id 232}
  #:db{:id 233}
  #:db{:id 234}
  #:db{:id 235}
  #:db{:id 236}
  #:db{:id 237}
  #:db{:id 238}
  #:db{:id 239}
  #:db{:id 241}
  #:db{:id 242}
  #:db{:id 243}
  #:db{:id 244}
  #:db{:id 245}
  #:db{:id 246}
  #:db{:id 247}
  #:db{:id 248}
  #:db{:id 249}
  #:db{:id 250}
  #:db{:id 251}
  #:db{:id 252}
  #:db{:id 253}
  #:db{:id 254}
  #:db{:id 255}
  #:db{:id 256}
  #:db{:id 257}
  #:db{:id 258}
  #:db{:id 264}],
 :block/uid "4b5aacda6",
 :create/time 1632844251122,
 :edit/time 1632845324097,
 :node/title "Break this page"}
#:db{:id 258}
#:db{:id 258}
()
```

Code for the repro is at https://github.com/filipesilva/datahike-broken-ref/blob/master/src/repro.clj, but depends on the database also stored in the repository.

```
(ns repro
  (:require [clojure.pprint :as pprint]
            [datahike.api :as d]))

(defn repro
  []
  (let [config {:store {:backend :file
                        :path    "athens-dockerized_datahike-db/_data"}}
       conn   (d/connect config)]

    ;; Entity 194 has a reference to entity 258 in its :block/children
    (pprint/pprint (d/pull @conn '[*] 194))

    ;; But entity 258 doesn't seem to have any attributes.
    (pprint/pprint (d/pull @conn '[*] 258))
    (pprint/pprint (d/entity @conn 258))

    ;; Entity 258 doesn't seem to have any datoms at all.
    (pprint/pprint (filter (comp #{258} first) (d/datoms @conn :eavt)))

    (d/release conn)))

(defn run [_]
  (repro))

(comment
  (run nil))

```

cc @neotyk

**Comment by jsmassa** [comment] 2021-09-30 15:28
I will have a look what's happening here.

**Comment by jsmassa** [comment] 2021-10-01 12:05
Can you tell us which operation you used to remove the entity?

There are three kind operations that perform retractions of datoms
- `:db/retract` which simple removes exactly the datom defined
- `:db/retractAttribute` which removes all datoms with the given entity-attribute pair
- `:db/retractEntity` which removes all datoms with the given entity-id as well as all references to it

If the problem is occuring with the latter, there is indeed a bug here, otherwise it is the expected behavior at the moment due to performance reasons.

**Comment by filipesilva** [comment] 2021-10-01 13:23
@jsmassa I don't know which exact operation led to this state, as we only realized we were in a bad state a while in. If I had to bet it was `:db/RetractEntity` though.

**Comment by jsmassa** [comment] 2021-10-01 14:13
I just tested it on the project you provided. `:db/retractEntity` seems to be working, i.e. it deletes the reference as well. I'd guess the state must have been produced by using `:db/retract` then.

**Comment by kordano** [comment] 2021-11-11 15:26
Since the issue was answered I'm closing this issue.

**Closed by kordano** 2021-11-11 15:26 UTC
