### ISSUE TITLE
Running benchmarks

### ISSUE THREAD

**Issue by julienfantin** [replikativ/datahike#102] opened 2019-12-06 04:30 UTC
Was curious to run the project benchmarks but ran into some issues:

1. The `bench/bench` script failed with:

```
~/projects/github.com/datahike/bench
$ ./bench jvm
Running all within {BENCH_PROJECT datahike-jvm, BENCH_BUILD 637/734e9bc/v0.2.0-beta-192} ...
Reflection warning, /private/var/folders/3h/xfhx4g953mv6l68c_qywbz4m0000gn/T/form-init9149125008979784840.clj:1:987 - call to static method invokeStaticMethod on clojure.lang.Reflector can't be resolved (argument types: unknown, java.lang.String, unknown).
Can't find 'datahike.bench/bench-all' as .class or .clj for lein run: please check the spelling.
Syntax error (FileNotFoundException) compiling at (/private/var/folders/3h/xfhx4g953mv6l68c_qywbz4m0000gn/T/form-init9149125008979784840.clj:1:125).
Could not locate datahike/bench__init.class, datahike/bench.clj or datahike/bench.cljc on classpath.

Full report at:
/var/folders/3h/xfhx4g953mv6l68c_qywbz4m0000gn/T/clojure-8276012869529528117.edn
Exception in thread "main" clojure.lang.ExceptionInfo: ERROR {:cmd ("lein" "trampoline" "run" "-m" "datahike.bench/bench-all"), :code 1}, compiling:(/Users/julien/projects/github.com/datahike/bench/./bench:146:1)
        at clojure.lang.Compiler.load(Compiler.java:7239)
        at clojure.lang.Compiler.loadFile(Compiler.java:7165)
        at clojure.main$load_script.invoke(main.clj:275)
        at clojure.main$script_opt.invoke(main.clj:337)
        at clojure.main$main.doInvoke(main.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: ERROR {:cmd ("lein" "trampoline" "run" "-m" "datahike.bench/bench-all"), :code 1}
        at clojure.core$ex_info.invoke(core.clj:4593)
        at user$run.doInvoke(bench:46)
        at clojure.lang.RestFn.invoke(RestFn.java:482)
        at user$run_bench.invoke(bench:109)
        at user$eval41.invoke(bench:150)
        at clojure.lang.Compiler.eval(Compiler.java:6782)
        at clojure.lang.Compiler.load(Compiler.java:7227)
        ... 9 more
```

2. The `bench/bench.clj` seemed like a more up-to-date version but that didn't work either:

```
~/projects/github.com/datahike/bench
$ clojure bench.clj
version         add-1   add-5   add-all         init    retract-5       q1      q2      q3      q4      qpred1  qpred2
latest-jvm      Syntax error (FileNotFoundException) compiling at (datahike/index/hitchhiker_tree.cljc:1:1).
Could not locate hitchhiker/tree/core__init.class, hitchhiker/tree/core.clj or hitchhiker/tree/core.cljc on classpath.

Full report at:
/var/folders/3h/xfhx4g953mv6l68c_qywbz4m0000gn/T/clojure-8743702676462937440.edn
Syntax error (ExceptionInfo) compiling at (bench.clj:124:1).
ERROR

Full report at:
/var/folders/3h/xfhx4g953mv6l68c_qywbz4m0000gn/T/clojure-5897924001872324705.edn
```

3. Finally I did find the `examples/performance` directory but I'm unable to start a repl there either because datahike's `db/id` data reader seems to conflict with datomic's:

```
~/projects/github.com/datahike/examples/performance
$ lein repl
clojure.lang.ExceptionInfo: Conflicting data-reader mapping {:url #object[java.net.URL 0x6e6f2380 "jar:file:/Users/j
ulien/.m2/repository/io/replikativ/datahike/0.2.0-SNAPSHOT/datahike-0.2.0-SNAPSHOT.jar!/data_readers.clj"], :conflic
t db/id, :mappings {db/id #'datomic.db/id-literal, db/fn #'datomic.function/construct, base64 #'datomic.codec/base-6
4-literal, datahike/Datom #'datahike.datom/datom-from-reader}}
        at clojure.core$load_data_reader_file$fn__8787.invoke(core.clj:7824)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8125.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8125.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6828)
        at clojure.core$load_data_reader_file.invokeStatic(core.clj:7813)
        at clojure.core$load_data_reader_file.invoke(core.clj:7804)
        at clojure.core.protocols$fn__8144.invokeStatic(protocols.clj:168)
        at clojure.core.protocols$fn__8144.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8099$G__8094__8108.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8131.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8131.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6828)
        at clojure.core$load_data_readers$fn__8794.invoke(core.clj:7835)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Var.alterRoot(Var.java:308)
        at clojure.core$alter_var_root.invokeStatic(core.clj:5510)
        at clojure.core$alter_var_root.doInvoke(core.clj:5505)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.core$load_data_readers.invokeStatic(core.clj:7834)
        at clojure.core$fn__8797.invokeStatic(core.clj:7839)
        at clojure.core$fn__8797.invoke(core.clj:7839)
        at clojure.core__init.load(Unknown Source)
        at clojure.core__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2207)
        at clojure.lang.RT.classForName(RT.java:2216)
        at clojure.lang.RT.loadClassForName(RT.java:2235)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:428)
        at clojure.lang.RT.doInit(RT.java:471)
        at clojure.lang.RT.<clinit>(RT.java:338)
        at clojure.main.<clinit>(main.java:20)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2207)
        at clojure.lang.RT.classForName(RT.java:2216)
        at clojure.lang.RT.loadClassForName(RT.java:2235)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:428)
        at clojure.lang.RT.doInit(RT.java:471)
        at clojure.lang.RT.<clinit>(RT.java:338)
        at clojure.main.<clinit>(main.java:20)
Subprocess failed
```

Could we add some instructions on how to run benchmarks and/or performance tests?

**Comment by whilo** [comment] 2019-12-06 09:15
Thanks for reporting the issue! The benchmark scripts are on our agenda after the next bugfix release. @jsmassa will do measurements and provide automatic benchmark scripts. 

@julienfantin Is there something specific that you are interested in?

**Comment by kordano** [comment] 2019-12-06 13:28
We will probably move the whole performance suite into a separate project where we can also publish the results.

**Comment by julienfantin** [comment] 2019-12-06 16:33
@whilo I noticed you'd made progress towards restoring ClojureScript compatibility so I was really curious to see how the performance compares to DataScript in browsers and Datomic on the JVM. IMHO a main consideration for early adopters is knowing what the performance trade-offs are compared to the alternatives, which is something the README does not currently address.

@kordano Glad you're planning on investing in benchmarks! However I believe there is something to be said for keeping them in the main repo so they stay current and can also double as a performance regression tests to be used in CI or development.

**Comment by whilo** [comment] 2019-12-16 07:58
I agree that performance tests should be part of the core repository and ideally tests should fail on performance regressions.

**Comment by whilo** [comment] 2020-01-18 21:09
@julienfantin Personally I think you should not make decisions based on performance unless you buy into a solution heavily. The performance problems that pop up later are often difficult to judge, but everybody wants to believe that they need to scale massively up, because that would mean they are super successful. This is the main reason why MongoDB exists. A goal of datahike is to be compatible with both Datomic and DataScript as much as possible and it should not be difficult to port between either of those. But I agree that we need to document and automate performance tests and we very much care about having top performance and horizontal scaling. Btw. any help is welcome! :)

**Comment by whilo** [comment] 2020-04-18 00:40
@julienfantin This should be addressed in https://github.com/replikativ/datahike-benchmark. We will run these tests in our CI/CD pipeline. Please feel free to open any further issues there.

**Closed by whilo** 2020-04-18 00:40 UTC
