### ISSUE TITLE
Datoms disappearing upon reconnection

### ISSUE THREAD

**Issue by mainej** [replikativ/datahike#338] opened 2021-05-25 21:33 UTC
I have a (boolean) attribute that exists on several entities. I can set and query that attribute, and as long as I have a cached connection, things appear consistent. But as soon as I reconnect (`d/connect`) the attribute reverts to an earlier value _for some but not all of the entities_. If I continue to transact data with the new connection, then reconnect, again some of updates will be lost, though on a _different_ set of entities.

I am using version 0.3.6.

This may not be relevant, but I'll include it for completeness. I've been comparing the `:eavt` indices between the two connections. For each transaction that sets the attribute, on the cached connection I see two Datoms: one for the updated value of the attribute, and one for the transaction itself, setting `:db/txInstant`. On the fresh connection, the index has only one Datom from that transaction, the one that sets `:db/txInstant`. That is, on the fresh connection the transaction exists, but isn't updating the entity. I don't know the hitchhiker tree format well enough to research whether the transaction isn't being fully persisted, or if it is persisted but fails to be applied when re-connecting.

Any guidance would be appreciated. As is, my database is unusable because it keeps losing data.

**Comment by kordano** [comment] 2021-05-26 16:13
Hi @mainej , could you give share your database schema? I'll have a look at the issue then.

**Comment by mainej** [comment] 2021-05-26 21:54
@kordano thanks for taking a look at this.

This is hard to replicate, but I've come up with something that seems to do it reliably. Note that in the following code, the sequence of operations is important. The problem doesn't happen if steps are re-ordered or combined.

```clojure
(ns debug
  (:require [datahike.api :as d]
            [datahike.db :as db]
            [clojure.data :as data]))

(defn ident-eid [db ident]
  (d/q '[:find ?e .
         :in $ ?ident
         :where [?e :db/ident ?ident]]
       db ident))

(defn random-uuid []
  (java.util.UUID/randomUUID))

(def ascii-ish
  (map char (concat (range 48 58) (range 65 91) (range 97 123))))
(defn random-char []
  (rand-nth ascii-ish))
(defn random-string [length]
  (apply str (repeatedly length random-char)))

(defn ent-ids [db]
  (d/q '[:find [?e ...]
         :where
         [?e :ent/id]]
       db))

(comment
  (let [cfg {:store {:backend :file :path "/tmp/replicate-bug"}}]
    (when-not (d/database-exists? cfg)
      (d/create-database cfg))
    (let [conn (d/connect cfg)]
      ;; initialize data, only once
      (when-not (ident-eid (d/db conn) :ent/id)
        (d/transact conn {:tx-data [{:db/ident       :ent/id
                                     :db/valueType   :db.type/uuid
                                     :db/cardinality :db.cardinality/one
                                     :db/unique      :db.unique/identity
                                     :db/doc         "The entity ID."}
                                    {:db/ident       :ent/active?
                                     :db/valueType   :db.type/boolean
                                     :db/cardinality :db.cardinality/one
                                     :db/doc         "Whether the entity is active."}
                                    {:db/ident       :meta/space-taker
                                     :db/valueType   :db.type/string
                                     :db/cardinality :db.cardinality/one
                                     :db/doc         "Takes up some space in the db"}]})
        ;; make a few entities
        (d/transact conn {:tx-data (map (fn [_]
                                          {:ent/id (random-uuid)})
                                        (range 8))})

        ;; take up some space in the db
        ;; NOTE: problem only happens if there is some extra data in the db
        (d/transact conn {:tx-data (map (fn [_]
                                          {:meta/space-taker (random-string 250)})
                                        (range 1000))})

        ;; activate all entities
        ;; NOTE: problem only happens if `:ent/active?` is set to true as an
        ;; update, not if it set when the entity is created.
        (d/transact conn {:tx-data (map (fn [eid]
                                          {:db/id      eid
                                           :ent/active? true})
                                        (ent-ids (d/db conn)))}))
      ;; later on, deactivate some entities
      (d/transact conn {:tx-data (->> (ent-ids (d/db conn))
                                      sort
                                      (take 5)
                                      (map (fn [eid]
                                             [:db/add eid :ent/active? false])))})

      ;; Some of the entities should be deactivated. This should be true whether
      ;; using a cached or fresh connection
      (let [cached-db (d/db conn)
            fresh-db  (d/db (d/connect cfg))]
        ;; in my testing, this assertion fails:
        ;; Assert failed: active should be same in cached 3 and fresh 8
        ;; (= (count (active cached-db)) (count (active fresh-db)))
        (let [active (fn [db]
                       (d/q '[:find [?e ...]
                              :where
                              [?e :ent/active? true]]
                            db))]
          (assert (= (count (active cached-db))
                     (count (active fresh-db)))
                  (str "active should be same in cached " (count (active cached-db))
                       " and fresh " (count (active fresh-db)))))
        ;; If the first assertion is commented out, this assertion fails,
        ;; showing that the entities that were deactivated are still active on
        ;; the fresh connection.
        (let [idx                        (fn [db]
                                           (db/-datoms db :eavt []))
              [only-cached only-fresh _] (data/diff (set (idx cached-db))
                                                    (set (idx fresh-db)))]
          (assert (and (nil? only-cached)
                       (nil? only-fresh))
                  [only-cached only-fresh]))))))

```

**Comment by kordano** [comment] 2021-05-27 11:17
Thanks for the detailed info. I'll get right to it.

**Comment by kordano** [comment] 2021-05-31 07:36
I could reproduce your problem @mainej and tried to figure out when and why this started to happen. It seems that the error was introduced after version 0.3.2, maybe through our upsert optimizations. So, if you are using Datahike 0.3.2, you should be fine. In the meantime I'm working on solving this issue with the current version.

**Comment by mainej** [comment] 2021-06-02 16:05
Thanks for researching @kordano. I can't revert to 0.3.2, as I was experiencing https://github.com/replikativ/datahike/issues/122. The fix for that wasn't merged until 0.3.6. 

Good to know that it wasn't present in 0.3.2 though. If I get a chance, I might `git bisect` through the datahike history to see exactly when the problem appears.

**Comment by grischoun** [comment] 2021-06-03 16:34
Bisecting was a good idea @mainej. I did it and it is when we moved to the following hitchhiker-tree branch that the bug happens. That is from Datahike commit `01125e3`. 

```
{io.replikativ/hitchhiker-tree               {:git/url "https://github.com/replikativ/hitchhiker-tree.git"}
                                                               :sha "4d332a2a00d460ec59ab8cc5468eb7272e99fe3e"}
```

The bug still needs investigation though.

**Comment by whilo** [comment] 2021-06-03 21:42
The bump in the hitchhiker-tree also corresponds to a bump back to `konserve` version `0.5.1` from https://github.com/replikativ/konserve/commit/f904359fc91fd6e6c36b9cd320d7beadaf5a15b7. I am not sure whether this is the reason, but it might be worth trying whether the bug goes away when manually bumping the `konserve` dependency in your project to `0.6.0-alpha3`.

**Comment by grischoun** [comment] 2021-06-08 19:30
Closing because this issue is fixed in PR #320 .

**Closed by grischoun** 2021-06-08 19:30 UTC
Labels: bug

**Comment by arthurbarroso** [comment] 2021-09-06 17:27
I am experiencing a similar issue but am using `datahike-postgres` (and am using datahike version `0.3.6` and datahike-postgres version `0.1.0`):
```clojure
;; Add a pre-existing `:health/question` to this entity
(d/transact db 
  [[:db/add [:health/uuid (java.util.UUID/fromString "f13f2a9d-0b35-4b7b-a731-e34adb3a64d9")] 
    :health/question 98]])
;;`health/question` will exist
(d/pull @db '[*] [:health/uuid (java.util.UUID/fromString "f13f2a9d-0b35-4b7b-a731-e34adb3a64d9")])
;; Pulling again after reloading the server (or re-starting the application/repl/database-state) 
;; will return the entity with no `:health/question`
(d/pull @db '[*] [:health/uuid (java.util.UUID/fromString "f13f2a9d-0b35-4b7b-a731-e34adb3a64d9")])
```

My "database" currently looks like this:
```clojure
(defn create-config [{:keys [host port user password dbname]}]
  {:store {:backend :pg
           :host host
           :port port
           :username user
           :password password
           :path (str "/" dbname)}})

(def schema [;;health-check
             ;;health/uuid
             {:db/ident :health/uuid
              :db/valueType :db.type/uuid
              :db/unique :db.unique/identity
              :db/cardinality :db.cardinality/one}
             ;;health/created_at
             {:db/ident :health/created_at
              :db/valueType :db.type/instant
              :db/cardinality :db.cardinality/one}
             ;;health/question
             {:db/ident :health/question
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/many}
             ;;questions
             ;;question/uuid
             {:db/ident :question/uuid
              :db/valueType :db.type/uuid
              :db/unique :db.unique/identity
              :db/cardinality :db.cardinality/one}
             ;;question/created_at
             {:db/ident :question/created_at
              :db/valueType :db.type/instant
              :db/cardinality :db.cardinality/one}
             ;;question/content
             {:db/ident :question/content
              :db/valueType :db.type/string
              :db/cardinality :db.cardinality/one}
             ;;question/answer
             {:db/ident :question/answer
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/many}
             ;;answers
             ;;answer/uuid
             {:db/ident :answer/uuid
              :db/valueType :db.type/uuid
              :db/unique :db.unique/identity
              :db/cardinality :db.cardinality/one}
             ;;answer/rating
             {:db/ident :answer/rating
              :db/valueType :db.type/bigint
              :db/cardinality :db.cardinality/one}
             ;;answer/created_at
             {:db/ident :answer/created_at
              :db/valueType :db.type/instant
              :db/cardinality :db.cardinality/one}])

(defn create-database [config]
  (d/create-database config))

(defn create-connection [environment]
  (let [config (create-config environment)]
    (when-not (d/database-exists? config)
      (create-database (merge config)))
    (let [connection (d/connect config)]
      (d/transact connection schema)
      connection)))
```

Can you guys spot some mistake on my schema or something I am missing? I'm not sure why this is happening. It seems that the datoms are being "written" to the cached connection but not to my "real" one (therefore never being written to postgres)

**Comment by arthurbarroso** [comment] 2021-09-06 18:06
I am experiencing a similar issue but am using `datahike-postgres`  (datahike version `0.3.6` and datahike-postgres version `0.1.0`):
```clojure
;; Add a pre-existing `:health/question` to this entity
(d/transact db 
  [[:db/add [:health/uuid (java.util.UUID/fromString "f13f2a9d-0b35-4b7b-a731-e34adb3a64d9")] 
    :health/question 98]])
;;`health/question` will exist
(d/pull @db '[*] [:health/uuid (java.util.UUID/fromString "f13f2a9d-0b35-4b7b-a731-e34adb3a64d9")])
;; Pulling again after reloading the server (or re-starting the application/repl/database-state) 
;; will return the entity with no `:health/question`
(d/pull @db '[*] [:health/uuid (java.util.UUID/fromString "f13f2a9d-0b35-4b7b-a731-e34adb3a64d9")])
```

My "database" currently looks like this:
```clojure
(defn create-config [{:keys [host port user password dbname]}]
  {:store {:backend :pg
           :host host
           :port port
           :username user
           :password password
           :path (str "/" dbname)}})

(def schema [;;health-check
             ;;health/uuid
             {:db/ident :health/uuid
              :db/valueType :db.type/uuid
              :db/unique :db.unique/identity
              :db/cardinality :db.cardinality/one}
             ;;health/created_at
             {:db/ident :health/created_at
              :db/valueType :db.type/instant
              :db/cardinality :db.cardinality/one}
             ;;health/question
             {:db/ident :health/question
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/many}
             ;;questions
             ;;question/uuid
             {:db/ident :question/uuid
              :db/valueType :db.type/uuid
              :db/unique :db.unique/identity
              :db/cardinality :db.cardinality/one}
             ;;question/created_at
             {:db/ident :question/created_at
              :db/valueType :db.type/instant
              :db/cardinality :db.cardinality/one}
             ;;question/content
             {:db/ident :question/content
              :db/valueType :db.type/string
              :db/cardinality :db.cardinality/one}
             ;;question/answer
             {:db/ident :question/answer
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/many}
             ;;answers
             ;;answer/uuid
             {:db/ident :answer/uuid
              :db/valueType :db.type/uuid
              :db/unique :db.unique/identity
              :db/cardinality :db.cardinality/one}
             ;;answer/rating
             {:db/ident :answer/rating
              :db/valueType :db.type/bigint
              :db/cardinality :db.cardinality/one}
             ;;answer/created_at
             {:db/ident :answer/created_at
              :db/valueType :db.type/instant
              :db/cardinality :db.cardinality/one}])

(defn create-database [config]
  (d/create-database config))

(defn create-connection [environment]
  (let [config (create-config environment)]
    (when-not (d/database-exists? config)
      (create-database (merge config)))
    (let [connection (d/connect config)]
      (d/transact connection schema)
      connection)))
```

Can you guys spot any mistake on my schema or anything I am missing? I'm not sure why this is happening. It seems that the datoms are being "written" to the cached connection but not to my "real" one (therefore never being written to postgres)

Tried upgrading to `0.3.7-SNAPSHOT` but this is still happenning
